<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class AddAdmsDamanAddressSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        // Variável para receber os dados a serem inseridos
        $data = [];

        // Variável para receber os dados que devem ser validados antes de cadastrar
        $addresses = [
            [
                'zip_code'      => '66055-200',
                'street'        => 'Travessa Don Romoaldo de Seixas',
                'number'        => '23',
                'complement'    => null,
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66080-000',
                'street'        => 'Av. Pedro Miranda',
                'number'        => '2566',
                'complement'    => 'Esquina com a Alferes Costa',
                'neighborhood'  => 'Pedreira',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66050-350',
                'street'        => 'Rua Municipalidade',
                'number'        => '1157',
                'complement'    => null,
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66050-350',
                'street'        => 'Rua Municipalidade',
                'number'        => '1634',
                'complement'    => null,
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67110-000',
                'street'        => 'Rod. BR-316',
                'number'        => '04',
                'complement'    => 'Casa',
                'neighborhood'  => 'Coqueiro',
                'city'          => 'Ananindeua',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66093-026',
                'street'        => 'Av. Duque de Caxias',
                'number'        => '500',
                'complement'    => null,
                'neighborhood'  => 'Marco',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66085-024',
                'street'        => 'Av. Pedro Miranda',
                'number'        => '2037',
                'complement'    => null,
                'neighborhood'  => 'Pedreira',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '08579-000',
                'street'        => 'Estrada do Bonsucesso',
                'number'        => '6001',
                'complement'    => null,
                'neighborhood'  => 'Rio Abaixo',
                'city'          => 'Itaquaquecetuba',
                'state'         => 'SP',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66093-682',
                'street'        => 'Tv. Mauriti',
                'number'        => '4834 C',
                'complement'    => null,
                'neighborhood'  => 'Marco',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66055-000',
                'street'        => 'Rua Conego Jeronimo Pimentel',
                'number'        => '183',
                'complement'    => null,
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66093-020',
                'street'        => 'Av. Almirante Barroso',
                'number'        => '280',
                'complement'    => null,
                'neighborhood'  => 'São Bras',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66635-110',
                'street'        => 'Rod. Augusto Montenegro - Km 07',
                'number'        => '1',
                'complement'    => 'Loja Frente',
                'neighborhood'  => 'Parque Verde',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66033-420',
                'street'        => 'Av. Roberto Camelier',
                'number'        => '636',
                'complement'    => null,
                'neighborhood'  => ' Jurunas',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66083-390',
                'street'        => 'Tv. Lomas Valentina',
                'number'        => '12',
                'complement'    => null,
                'neighborhood'  => 'Sacramenta',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66113-000',
                'street'        => 'Av. Senador Lemos',
                'number'        => '2227',
                'complement'    => null,
                'neighborhood'  => 'Telégrafo',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68741-000',
                'street'        => 'Av. Presidente Getulio Vargas - KM 60',
                'number'        => 'S/N',
                'complement'    => null,
                'neighborhood'  => 'Cristo Redentor',
                'city'          => 'Castanhal',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67110-280',
                'street'        => 'Rua da Pedreirinha',
                'number'        => '777',
                'complement'    => null,
                'neighborhood'  => 'Guanabara',
                'city'          => 'Ananindeua',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66123-050',
                'street'        => 'Av. Doutor Freitas',
                'number'        => '101',
                'complement'    => null,
                'neighborhood'  => 'Sacramenta',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68795-000',
                'street'        => 'Rod. BR-316 KM 25',
                'number'        => '25',
                'complement'    => null,
                'neighborhood'  => 'Canutama',
                'city'          => 'Benevides',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67200-000',
                'street'        => 'Rod. Alca Viaria - KM 2',
                'number'        => 'S/N',
                'complement'    => 'Galpão',
                'neighborhood'  => 'São João',
                'city'          => 'Marituba',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66063-060',
                'street'        => 'Av. Conselheiro Furtado',
                'number'        => '3072',
                'complement'    => 'Terreo',
                'neighborhood'  => 'Cremação',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67113-000',
                'street'        => 'Rod. Br 316 - KM 3',
                'number'        => 'S/N',
                'complement'    => null,
                'neighborhood'  => 'Coqueiro',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66023-570',
                'street'        => 'Tv.  São Pedro',
                'number'        => '239',
                'complement'    => 'Sala B',
                'neighborhood'  => 'Campina',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66033-010',
                'street'        => 'Rua São Miguel',
                'number'        => '650',
                'complement'    => null,
                'neighborhood'  => 'Batista Campos',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67203-007',
                'street'        => 'Passagem Sao Cristovão',
                'number'        => '100',
                'complement'    => null,
                'neighborhood'  => 'São João',
                'city'          => 'Marituba',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66825-000',
                'street'        => 'Rod. Arthur Bernardes',
                'number'        => '15.154',
                'complement'    => null,
                'neighborhood'  => 'Tapanã',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67030-130',
                'street'        => 'Rua São João Canuto',
                'number'        => '240',
                'complement'    => null,
                'neighborhood'  => 'Centro',
                'city'          => 'Ananindeua',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66060-160',
                'street'        => 'Rua Domingos Marreiros',
                'number'        => '1644',
                'complement'    => 'loja',
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67035-150',
                'street'        => 'Rua Vitoria',
                'number'        => '2150',
                'complement'    => 'Casa 09 a',
                'neighborhood'  => 'Distrito Industrial',
                'city'          => 'Ananindeua',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66113-000',
                'street'        => 'Av. Senador Lemos',
                'number'        => '1926',
                'complement'    => 'Baixo',
                'neighborhood'  => 'Telégrafo',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66123-000',
                'street'        => 'Av. Pedro Alvares Cabral',
                'number'        => '5000',
                'complement'    => 'Sala 02',
                'neighborhood'  => 'Sacramenta',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67133-185',
                'street'        => 'Tv. We-33 (Cidade Nova Iv)',
                'number'        => '192',
                'complement'    => null,
                'neighborhood'  => 'Cidade Nova',
                'city'          => 'Ananindeua',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66063-540',
                'street'        => 'Rua Silva Castro',
                'number'        => '336',
                'complement'    => 'Letra a',
                'neighborhood'  => 'Guamá',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66083-000',
                'street'        => 'Travessa Mauriti',
                'number'        => '536',
                'complement'    => null,
                'neighborhood'  => 'Telégrafo',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '84043-000',
                'street'        => 'Visconde de Maua',
                'number'        => '3460',
                'complement'    => null,
                'neighborhood'  => 'Colonia Dona Luiza',
                'city'          => 'Ponta Grossa',
                'state'         => 'PR',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67203-020',
                'street'        => 'Rod. Alça Viária - KM 3',
                'number'        => '3087',
                'complement'    => null,
                'neighborhood'  => 'São João',
                'city'          => 'Marituba',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66095-491',
                'street'        => 'Av. João Paulo II',
                'number'        => '90',
                'complement'    => null,
                'neighborhood'  => 'Curió Utinga',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66045-205',
                'street'        => 'Av. Engenheiro Fernando Guilhon',
                'number'        => '2383',
                'complement'    => 'Anexo 1',
                'neighborhood'  => 'Cremação',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66120-000',
                'street'        => 'Av. Senador Lemos',
                'number'        => '3153',
                'complement'    => 'Piso 1 Loja 27',
                'neighborhood'  => 'Sacramenta',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66050-000',
                'street'        => 'Av. Senador Lemos',
                'number'        => '337',
                'complement'    => null,
                'neighborhood'  => 'Umarizal',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68376-725',
                'street'        => 'Passagem IV',
                'number'        => '1245',
                'complement'    => null,
                'neighborhood'  => 'Ibiza',
                'city'          => 'Altamira',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68041-140',
                'street'        => 'Av. São Sebastião',
                'number'        => '2882',
                'complement'    => 'Setor A',
                'neighborhood'  => 'Laguinho',
                'city'          => 'Santarém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66095-050',
                'street'        => 'Tv. Barão do Triunfo',
                'number'        => '3540',
                'complement'    => 'Edif Infinity Sala 2404',
                'neighborhood'  => 'Marco',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '67113-000',
                'street'        => 'Rod. Br 316 - KM 2',
                'number'        => '507',
                'complement'    => null,
                'neighborhood'  => 'Ananindeua',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68375-343',
                'street'        => 'Rod. Transamazonica - KM 2',
                'number'        => '123',
                'complement'    => 'Sala C',
                'neighborhood'  => 'Liberdade',
                'city'          => 'Altamira',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '68373-360',
                'street'        => 'Rua José Ribeiro Alves',
                'number'        => '3490',
                'complement'    => null,
                'neighborhood'  => 'Jardim Independente I',
                'city'          => 'Altamira',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66045-000',
                'street'        => 'Tv. Padre Eutiquio',
                'number'        => '2927',
                'complement'    => null,
                'neighborhood'  => 'Condor',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],

            // Usuários
            [
                'zip_code'      => '66045-000',
                'street'        => 'Tv. Padre Eutiquio',
                'number'        => '2927',
                'complement'    => null,
                'neighborhood'  => 'Condor',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66045-000',
                'street'        => 'Tv. Padre Eutiquio',
                'number'        => '2927',
                'complement'    => null,
                'neighborhood'  => 'Condor',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66045-000',
                'street'        => 'Tv. Padre Eutiquio',
                'number'        => '2927',
                'complement'    => null,
                'neighborhood'  => 'Condor',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'zip_code'      => '66045-000',
                'street'        => 'Tv. Padre Eutiquio',
                'number'        => '2927',
                'complement'    => null,
                'neighborhood'  => 'Condor',
                'city'          => 'Belém',
                'state'         => 'PA',
                'created_at'    => date('Y-m-d H:i:s'),
            ],
        ];

        // Percorrer o array com dados que devem ser validados antes de cadastrar
        foreach ($addresses as $address) {

            $data[] = [
                'zip_code' => $address['zip_code'],
                'street' => $address['street'],
                'number' => $address['number'],
                'complement' => $address['complement'],
                'neighborhood' => $address['neighborhood'],
                'city' => $address['city'],
                'state' => $address['state'],
                'created_at' => $address['created_at'],
            ];
        }

        // Obtém a tabela 'adms_daman_addresses' para inserir os registros
        $adms_daman_addresses = $this->table('adms_daman_addresses');

        // Insere os registros na tabela
        $adms_daman_addresses->insert($data)->save();
    }
}